# Generated by Django 4.0.1 on 2024-08-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=10)),
                ('prediction', models.FloatField()),
                ('close', models.FloatField()),
                ('actual', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
